version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  chats:
    build:
      context: ./chats-microservice
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      spring.datasource.url: ${DATABASE_URL}
      spring.datasource.username: ${DATABASE_USERNAME}
      spring.datasource.password: ${DATABASE_PASSWORD}
    depends_on:
      - postgres

  user:
    build:
      context: ./user-microservice
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      spring.datasource.url: ${DATABASE_URL
      spring.datasource.username: ${DATABASE_USERNAME}
      spring.datasource.password: ${DATABASE_PASSWORD}
    depends_on:
      - postgres

  front:
    build:
      context: ./frontend-messanger-microservice
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
volumes:
  pgdata: